import Head from "next/head";
import Image from "next/image";
import { GetStaticProps, InferGetStaticPropsType } from "next/types";
import classNames from "classnames";
import { getSiteData } from "../lib/api";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useDebugData } from "../lib/hooks";
import { Layout } from "../components/Layout";

export default function Index(
  props
): InferGetStaticPropsType<typeof getStaticProps> {
  useDebugData({ data: props });
  return (
    <Layout>
      <Head>
        <title>Link Palace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto h-full bg-cyan-100 ">Test</div>
    </Layout>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const data = await getSiteData();

  return {
    props: {
      data,
    },
  };
};
